### ISSUE TITLE
Annotation values should be quoted

### ISSUE THREAD

**Issue by jfelten** [sostheim/lbex#33]
Kubernetes will error out if the annotation values are not quoted.  The examples in README should be updated.

**Comment by sostheim** [comment]
Valid YAML (http://www.yamllint.com/) shown below:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nc-pod2-svc 
  labels:
    name: nc-pod2-svc
    app: nc-pod2
    version: 0.1.0
  annotations:
    kubernetes.io/loadbalancer-class: loadbalancer-lbex
    loadbalancer.lbex/port: 9090
    loadbalancer.lbex/service-pool: netcat
    loadbalancer.lbex/upstream-type: pod
spec:
  selector: 
    app: nc-pod2
  ports:
  - name: 
    port: 9090
```
Is rejected by Kubernetes `kubectl create -f ...`

```bash
$ kubectl create -f nc-pod2-svc.yaml 
Error from server (BadRequest): error when creating "nc-pod2-svc.yaml": Service in version "v1" cannot be handled as a Service: [pos 144]: json: expect char '"' but got char '9'
```
