### ISSUE TITLE
can't support multiple service ports with current strategy

### ISSUE THREAD

**Issue by sostheim** [sostheim/lbex#43]
Current Jenkin's spec:

```
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    name: jenkins
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    component: "{{.Release.Name}}-jenkins-master"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
    "kubernetes.io/loadbalancer-class": "{{ .Values.loadbalancer }}"
    {{- if .Values.master.externalPort }}
    "loadbalancer.lbex/port": "{{ .Values.master.externalPort }}"
    {{- end }}
spec:
  ports:
    - port: {{.Values.master.port}}
      name: masterport
      targetPort: {{.Values.master.port}}
    - port: {{.Values.agent.port}}
      targetPort: {{.Values.agent.port}}
      name: agentport
  selector:
    name: jenkins
  type: {{.Values.master.serviceType}}
```

Causes port mapping confusion:

```
cat /etc/nginx/conf.d/prod-jenkins.stream.conf
### WARNING: DO NOT EDIT THIS FILE - ALL CHANGES WILL BE LOST!        ###
### THE CONTENTS OF THIS FILE ARE GENERATED AND UPDATED AUTOMATICALLY ###
    upstream prod-jenkins-agentport {
        server 10.128.0.9:30913;
    }
    upstream prod-jenkins-masterport {
        server 10.128.0.9:31769;
    }
    server {
        listen 8080;
        proxy_pass prod-jenkins-agentport;
    }
    server {
        listen 8080;
        proxy_pass prod-jenkins-masterport;
    }
```
