### ISSUE TITLE
targetPort names are being checked as int's only.

### ISSUE THREAD

**Issue by sostheim** [sostheim/lbex#46]
In the following snippet:
```
spec:
 ports:
   -  name: masterport
     port: 8080
     targetPort: servicePort
```
The current implementation will attempt to convert the literal string 'servicePort' to an int and fail.  

This is standard supported Kubernetes configuration that needs to be supported in lbex.
