### ISSUE TITLE
LBEX will attempt to create a .conf file for non-NodePort type services 

### ISSUE THREAD

**Issue by maratoid** [sostheim/lbex#64]
Something like :

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/loadbalancer-class: loadbalancer-lbex
    loadbalancer-port.lbex/apache: "7843"
spec:
  ports:
  - name: apache
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: blah
  sessionAffinity: None
  type: ClusterIP
```

Will result in LBEX creating an .conf file with a ```:0``` port, thus preventing nginx restart and any of the other lbex services from functioning
